export const FETCH_ALL_HEATERS_REQUEST = 'FETCH_ALL_HEATERS_REQUEST';
export const FETCH_ALL_HEATERS_SUCCESS = 'FETCH_ALL_HEATERS_SUCCESS';
export const FETCH_ALL_HEATERS_FAILURE = 'FETCH_ALL_HEATERS_FAILURE';

export const DELETE_HEATER_REQUEST = 'DELETE_HEATER_REQUEST';
export const DELETE_HEATER_SUCCESS = 'DELETE_HEATER_SUCCESS';
export const DELETE_HEATER_FAILURE = 'DELETE_HEATER_FAILURE';

export const GET_HEATER_DATA_REQUEST = 'GET_HEATER_DATA_REQUEST';
export const GET_HEATER_DATA_SUCCESS = 'GET_HEATER_DATA_SUCCESS';
export const GET_HEATER_DATA_FAILURE = 'GET_HEATER_DATA_FAILURE';

export const UPDATE_HEATER_REQUEST = 'UPDATE_HEATER_REQUEST';
export const UPDATE_HEATER_SUCCESS = 'UPDATE_HEATER_SUCCESS';
export const UPDATE_HEATER_FAILURE = 'UPDATE_HEATER_FAILURE';

export const CANCEL_UPDATE = 'CANCEL_UPDATE';

export const CREATE_HEATER_REQUEST = 'CREATE_HEATER_REQUEST';
export const CREATE_HEATER_SUCCESS = 'CREATE_HEATER_SUCCESS';
export const CREATE_HEATER_FAILURE = 'CREATE_HEATER_FAILURE';

export const ADD_READING_REQUEST = 'ADD_READING_REQUEST';
export const ADD_READING_SUCCESS = 'ADD_READING_SUCCESS';
export const ADD_READING_FAILURE = 'ADD_READING_FAILURE';
